### ISSUE TITLE
Update the rollup section on docs

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#455] opened 2017-08-30 16:54 UTC
The section in this [link](https://docs.citusdata.com/en/v6.2/use_case_guide/real_time_dashboards.html?highlight=INSERT%20INTO%20SELECT#rollups) talks about how to do rollups prior to the support INSERT INTO SELECT feature. Now we don't need to use citus utility functions to rollup data between colocated shards (of colocated tables). INSERT INTO SELCT feature takes care of. Could we update this section by usage of INSERT INTO SELCT, just that it is simplified and easy to understand.

**Comment by sumedhpathak** [comment] 2017-08-30 17:06
Duplicate of https://github.com/citusdata/citus_docs/issues/198.

**Closed by sumedhpathak** 2017-08-30 17:06 UTC
