### ISSUE TITLE
Import useful blog posts as docs pages in "Articles" section

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#392] opened 2017-06-12 18:40 UTC
## Why are we implementing it? (sales eng)

There is a lot of great technical writing on our blog, but it can be harder to find than official documentation. Making docs pages out of posts allows them to be searched more easily, and prevents them from being "buried" over time.

## How does this work?

- [x] Review posts to find top 10 technical posts
- [ ] Identify which (potentially new) sections they should go in
- [ ] Remove redundant intro content that describes Citus, leaving the meat of the articles

**Comment by sumedhpathak** [comment] 2017-07-18 20:08
Dupe of #408

**Comment by begriffs** [comment] 2017-07-25 21:20
Here are my picks for content.

*Omitted*
* Blogs we already turned into docs pages
* General postgresql articles
* Pre-open source release stuff (pg_shard etc)
* New version announcements

___

Cloud / MX
* https://www.citusdata.com/blog/2016/09/22/announcing-citus-mx/
* https://www.citusdata.com/blog/2017/07/13/citus-addon-for-heroku/

Misc
* https://www.citusdata.com/blog/2017/01/17/parallel-indexing-with-citus/
* https://www.citusdata.com/blog/2016/10/10/outer-joins-in-citus/
* https://www.citusdata.com/blog/2016/07/25/sharding-json-in-postgres-and-performance/
* https://www.citusdata.com/blog/2016/06/10/scaling-mysql-with-citus/
* https://www.citusdata.com/blog/2016/04/28/scalable-product-search/

HLL
* https://www.citusdata.com/blog/2017/04/04/distributed_count_distinct_with_postgresql/
* https://www.citusdata.com/blog/2017/06/30/efficient-rollup-with-hyperloglog-on-postgres/
 
General realtime
* https://www.citusdata.com/blog/2016/11/29/event-aggregation-at-scale-with-postgresql/
* https://www.citusdata.com/blog/2016/08/30/citus-clouds-usage-of-citus-cloud/

@ozgune do you have any to add or remove?

**Comment by ozgune** [comment] 2017-07-27 18:33
@begriffs -- thanks for coming up this list.

I'd recommend adding the following posts to this list.

Multi-tenant

* https://www.citusdata.com/blog/2016/10/03/designing-your-saas-database-for-high-scalability/
* https://www.citusdata.com/blog/2016/08/10/sharding-for-a-multi-tenant-app-with-postgres/

Misc

* https://www.citusdata.com/blog/2017/03/10/how-to-scale-postgresql-on-aws/

I'd also recommend removing the following blog posts from this list.

* https://www.citusdata.com/blog/2016/06/10/scaling-mysql-with-citus -- we wouldn't want to guide our customers in this direction
* https://www.citusdata.com/blog/2016/09/22/announcing-citus-mx/ -- only if we already have similar content in our documentation in the Citus MX (Beta) section

**Comment by begriffs** [comment] 2017-07-27 23:27
@ozgune sounds good!

Hey about your SEO question, I think the easiest way to fix it without invasive changes to the code would be to add custom CloudFlare page rules for individual pages.

1. Decide whether the blog post or the docs page is considered the "main" content.
2. Then, set up CloudFlare page rules on the non-main content that add a Link rel=canonical http header pointing at the main content.

The only risk is if the main and duplicate content differed significantly then *perhaps* Google would think we were playing games and would penalize us. But otherwise both main and duplicate pages will contribute to the link score for the main one alone, making search results more likely to list the main content.

Also I'm not entirely sure that CloudFlare has the capability for such customized rules. I know it can do redirects and caching rules, but adding arbitrary http response headers...we'll see.

**Comment by ozgune** [comment] 2017-08-03 17:46
@begriffs -- Sounds good. For existing articles, we'd probably consider the blog post as the "main" content and our docs as the duplicate.

I had three quick questions.

1. Do you have a timeline in your mind for opening related PRs?
2. Are you planning to keep the blog post content the same across the blog post and main content?
3. Do you need any help from us (or an external consultant) to set up canonical http headers?

**Closed** 2017-10-06 01:35 UTC
Labels: in progress, organization
