### ISSUE TITLE
Locking problem in technical solution

### ISSUE THREAD

**Issue by lithp** [citusdata/citus_docs#208] opened 2016-11-14 23:39 UTC
Currently the insert script blocks `expire_old_request_data` from running. If the user leaves the insert script running in the background they might not understand why `expire_old_request_data` appears to hang forever.

**Comment by begriffs** [comment] 2017-02-23 23:35
Just putting the two code snippets together for reference.

```sql
DO $$
BEGIN
  LOOP
    INSERT INTO http_request (
        site_id, ingest_time, url, request_country,
        ip_address, status_code, response_time_msec
    ) VALUES (
        1, clock_timestamp(), 'http://example.com/path', 'USA',
        inet '88.250.10.123', 200, 10
    );
    PERFORM pg_sleep(random() * 2);
  END LOOP;
END $$;
```

Running the above in the background causes this function to block forever:
```sql
CREATE OR REPLACE FUNCTION expire_old_request_data() RETURNS void
AS $$
BEGIN
  SET citus.all_modification_commutative TO TRUE;
  PERFORM master_modify_multiple_shards(
            'DELETE FROM http_request WHERE ingest_time < now() - interval ''1 day'';');
  PERFORM master_modify_multiple_shards(
            'DELETE FROM http_request_1min WHERE ingest_time < now() - interval ''1 month'';');
END;
$$ LANGUAGE 'plpgsql';
```

Marco suggests I debug with [pg_locks](https://www.postgresql.org/docs/9.6/static/view-pg-locks.html).

**Comment by lithp** [comment] 2017-03-02 15:30
Hmm, I can't seem to reproduce this with master and 9.6.2

**Comment by begriffs** [comment] 2017-03-08 19:23
I got it to freeze on Cloud, but I can confirm that it works fine locally on PostgreSQL 9.6.1 and Citus 6.1-17.

@sumedhpathak should we close this issue?

**Comment by begriffs** [comment] 2017-03-14 20:45
Note to self: try this one more time on Cloud in case it has been updated in some way since last time.

**Comment by begriffs** [comment] 2017-03-15 18:27
Tried again on Cloud (Citus 6.1-17, PostgreSQL 9.6.2) and could not reproduce the old blocking behavior. Perhaps either the Citus or pg version has been upgraded since my last attempt and fixed the problem. Wish I had recorded those versions the first time around.

**Comment by begriffs** [comment] 2017-03-15 18:37
Interesting note: I reused the cloud instance to test another issue about the propagation of various kinds of DDL. I happened to have the fake data ingest function still running and noticed that this statement locked:

```sql
alter table http_request
add constraint recency_check
check (ingest_time > '1990-01-01'::date);
```

When I stopped the ingest function the alter table command was able to continue (it ultimately raised an error because that kind of constraint is not supported, but it was able to run).

**Comment by sumedhpathak** [comment] 2017-05-26 20:45
Ok, I can easily reproduce this for whatever reason. expire_old_request_data() hangs until I kill the ingest script.

**Comment by sumedhpathak** [comment] 2017-05-26 20:58
The writer:
`postgres  8629  8482  0 18:44 ?        00:00:02 postgres: postgres postgres [local] DO`                  

The reader:
`postgres 30339  8482  0 20:42 ?        00:00:00 postgres: postgres postgres [local] SELECT waiting     `

Looking at pg_locks:
```SQL
postgres=# select reader.objid, reader.mode as reader_mode, writer.mode as writer_mode from pg_locks writer, pg_locks reader where writer.pid = 8629 and reader.pid = 30339 and reader.objid = writer.objid;
 objid  |  reader_mode  |   writer_mode    
--------+---------------+------------------
 102009 | ExclusiveLock | ShareLock
 102009 | ShareLock     | ShareLock
 102009 | ExclusiveLock | RowExclusiveLock
 102009 | ShareLock     | RowExclusiveLock
```

**Comment by sumedhpathak** [comment] 2017-05-26 21:06
https://www.postgresql.org/docs/current/static/explicit-locking.html

`RowExclusiveLock` conflicts with both `ShareLock` and `ExclusiveLock`

```SQL
postgres=# select pg_blocking_pids(30339);
 pg_blocking_pids 
------------------
 {8629}
(1 row)

```

**Comment by sumedhpathak** [comment] 2017-05-26 21:11
These are all the locks held by the Ingest script:
```SQL
postgres=# select * from pg_locks where pid= 8629;
  locktype  | database | relation | page | tuple | virtualxid | transactionid | classid | objid  | objsubid | virtualtransaction | pid  |       mode       | granted | fastpath 
------------+----------+----------+------+-------+------------+---------------+---------+--------+----------+--------------------+------+------------------+---------+----------
 relation   |    13323 |    16622 |      |       |            |               |         |        |          | 3/11               | 8629 | AccessShareLock  | t       | t
 relation   |    13323 |    16622 |      |       |            |               |         |        |          | 3/11               | 8629 | RowExclusiveLock | t       | t
 virtualxid |          |          |      |       | 3/11       |               |         |        |          | 3/11               | 8629 | ExclusiveLock    | t       | t
 advisory   |    13323 |          |      |       |            |               |       0 | 102009 |        4 | 3/11               | 8629 | ShareLock        | t       | f
 advisory   |    13323 |          |      |       |            |               |       0 | 102009 |        5 | 3/11               | 8629 | RowExclusiveLock | t       | f
(5 rows)
```

**Comment by sumedhpathak** [comment] 2017-05-26 22:31
Its not clear to me why the ingest script is holding locks only on that one shardId.

**Comment by sumedhpathak** [comment] 2017-06-02 21:28
So looked at this a bit more, and it only happens when shard_replication_factor > 1. There isn't an actual problem here, and things work as expected. When the replication factor is > 1, the router executor takes a [`RowExclusiveLock` on the shard](https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/multi_router_executor.c#L221), while `master_modify_multiple_shards` is trying to take an `ExclusiveLock`, which conflict, and thus the expiration script blocks.

The script runs in its own transaction as a PL/PGSql function, and thus never releases the lock. The script also runs forever, so unless it is killed, it continues to block data expiration.

In the [Data Model section](https://docs.citusdata.com/en/v6.2/ref_arch/real_time_dashboards.html#data-model), we set shard_replication factor to 2, just to maintain parity with the previous setup. I don't think we need to do that any more? @lithp could you confirm that its OK to just allow the default 1 replication factor?

That resolves the locking issue for now.

**Comment by lithp** [comment] 2017-06-05 09:44
@sumedhpathak To the degree that I remember the technical solution I don't see any problem with using a replication factor of 1.

**Closed** 2017-07-07 17:06 UTC
Labels: bug, ready
