### ISSUE TITLE
Improve index page of docs

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#359] opened 2017-05-02 21:20 UTC
## Communication goals (e.g. detailed howto vs orientation)

Analytics show, unsurprisingly, that plenty of people view the front page of the docs. The page is currently not very interesting and dominated by a complete table of contents. Since the sidebar has the contents anyway, we can remove it from the index page and put more useful and enticing content there.

Just add

```rst
:hidden:
```

to each item on index.rst

**Comment by sumedhpathak** [comment] 2017-07-27 20:25
Dupe of #404. Closing.

**Closed by sumedhpathak** 2017-07-27 20:25 UTC
